services:
  openvpn:
    image: ronronan/openvpn:latest
    container_name: openvpn
    cap_add:
      - "NET_ADMIN"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - openvpn:/etc/openvpn
    ports:
      - 1194:1194/udp
    network_mode: bridge

volumes:
  openvpn:
    name: openvpn-data
